# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'MangaViewer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MangaViewer
pod 'AFNetworking','~> 3.0'
pod 'XLPagerTabStrip', '~> 5.0'

end
